name: Auto Updater

on:
  workflow_dispatch:

jobs:
  get_missing_versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install python requirements
        run: python -m pip install -r requirements.txt
      - name: Get missing versions
        run: python get_missing_versions.py
      - name: Show tags
        run: echo ${{ env.missing_tags }}

  build_and_push_for_tag:
    runs-on: ubuntu-latest
    needs: get_missing_versions
    strategy:
      matrix:
        tag: ${{ env.missing_tags }}

    steps:
      - uses: actions/checkout@v3
      - name: Create ${{ matrix.tag }}
        run: echo ${{ matrix.tag }}