name: Main CI

env:
  DOCKER_USER: "rossmaclean"
  APP_NAME: "cloudron-base-image"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: 'latest'

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker login
        run: docker login --username ${{ env.DOCKER_USER }} --password ${{ env.DOCKERHUB_TOKEN }}
      - name: Docker build
        run: docker buildx build -t ${{ env.DOCKER_USER }}/${{ env.APP_NAME }}:${{ github.event.inputs.version }} -t ${{ env.DOCKER_USER }}/${{ github.event.inputs.version }}:latest --platform=linux/amd64,linux/arm64 .
      - name: Docker push
        run: docker push --all-tags ${{ env.DOCKER_USER }}/${{ env.APP_NAME }}