name: Main CI

env:
  DOCKER_USER: "rossmaclean"
  APP_NAME: "cloudron-base-image"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: 'latest'

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build Push
        uses: rossmaclean/docker-build-push-action@v0.0.17
        with:
          docker-user: ${{ env.DOCKER_USER }}
          image-name: ${{ env.APP_NAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ github.event.inputs.version }}